--- # chrony-02.yml
- hosts: all
  vars:
    RedHat:
      chrony_package: chrony
      chrony_service: chronyd
      chrony_confdir: /etc
    Suse:
      chrony_package: chrony
      chrony_service: chronyd
      chrony_confdir: /etc
    Debian:
      chrony_package: chrony
      chrony_service: chrony
      chrony_confdir: /etc/chrony
    Ubuntu:
      chrony_package: chrony
      chrony_service: chrony
      chrony_confdir: /etc/chrony
  handlers:
    - name: restart chrony
      service:
        name: "{{ chrony_service }}"
        state: restarted
  tasks:
    - name: Set variables
      ansible.builtin.set_fact:
        chrony_package: "{{ lookup('vars', ansible_os_family).chrony_package }}"
        chrony_service: "{{ lookup('vars', ansible_os_family).chrony_service }}"
        chrony_confdir: "{{ lookup('vars', ansible_os_family).chrony_confdir }}"
    - name: Install chrony
      ansible.builtin.package:
        name: "{{ chrony_package }}"
        state: present
    - name: Edit chrony.conf
      ansible.builtin.copy:
        dest: "{{ chrony_confdir }}/chrony.conf"
        mode: '0644'
        content: |
          # /etc/chrony.conf
          server 0.fr.pool.ntp.org iburst
          server 1.fr.pool.ntp.org iburst
          server 2.fr.pool.ntp.org iburst
          server 3.fr.pool.ntp.org iburst
          driftfile /var/lib/chrony/drift
          makestep 1.0 3
          rtcsync
          logdir /var/log/chrony
    - name: Start and enable chrony
      ansible.builtin.service:
        name: "{{ chrony_service }}"
        state: started
        enabled: yes

      